version: '3'
services:
  postgres:
      image: postgres:9.5
      environment:
        POSTGRES_PASSWORD: 'postgres'
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 30s
        timeout: 30s
        retries: 3
  test_app:
    build: .
    ports:
      - '8080:8080'
    links:
      - postgres
    depends_on:
      - postgres
